# Generated by Django 3.2.5 on 2021-07-07 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ghazals',
            fields=[
                ('ghazal_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('tags', models.CharField(max_length=500)),
                ('singer', models.CharField(max_length=100)),
                ('ghazal', models.CharField(max_length=5000)),
            ],
        ),
    ]
