# Generated by Django 3.2.5 on 2021-07-07 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ghazals',
            old_name='singer',
            new_name='writer',
        ),
    ]
