# Generated by Django 3.2.5 on 2021-07-07 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_ghazal_ghazals_shayari'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ghazals',
            new_name='ghazal',
        ),
    ]
