# Generated by Django 3.2.5 on 2021-07-07 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_ghazals_ghazal'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ghazal',
            new_name='ghazal_home',
        ),
    ]
