# Generated by Django 3.2.5 on 2021-07-07 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_ghazal_ghazal_home'),
    ]

    operations = [
        migrations.CreateModel(
            name='famous_ghazal',
            fields=[
                ('ghazal_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('tags', models.CharField(max_length=500)),
                ('writer', models.CharField(max_length=100)),
                ('shayari', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='new_ghazal',
            fields=[
                ('ghazal_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('tags', models.CharField(max_length=500)),
                ('writer', models.CharField(max_length=100)),
                ('shayari', models.CharField(max_length=5000)),
            ],
        ),
    ]
